/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './counter.component';
const styles_CounterComponent:any[] = ([] as any[]);
export const RenderType_CounterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_CounterComponent,data:{}});
export function View_CounterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Counter'])),(_l()(),i0.ɵted((null as any),['\n\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['This is a simple example of an Angular component.'])),(_l()(),i0.ɵted((null as any),
          ['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'p',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Current count: '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'strong',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['',''])),(_l()(),
          i0.ɵted((null as any),['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'button',([] as any[]),(null as any),[[(null as any),'click']],(_v,en,
              $event) => {
            var ad:boolean = true;
            var _co:i1.CounterComponent = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.incrementCounter()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Increment'])),
      (_l()(),i0.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    var _co:i1.CounterComponent = _v.component;
    const currVal_0:any = _co.currentCount;
    _ck(_v,9,0,currVal_0);
  });
}
export function View_CounterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'counter',([] as any[]),
      (null as any),(null as any),(null as any),View_CounterComponent_0,RenderType_CounterComponent)),
      i0.ɵdid(49152,(null as any),0,i1.CounterComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const CounterComponentNgFactory:i0.ComponentFactory<i1.CounterComponent> = i0.ɵccf('counter',
    i1.CounterComponent,View_CounterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQW5ndWxhcjQvdGVzdEFvdEFwcDJXb3JraW5nL3Rlc3RBb3RBcHAyL0NsaWVudEFwcC9hcHAvY29tcG9uZW50cy9jb3VudGVyL2NvdW50ZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FuZ3VsYXI0L3Rlc3RBb3RBcHAyV29ya2luZy90ZXN0QW90QXBwMi9DbGllbnRBcHAvYXBwL2NvbXBvbmVudHMvY291bnRlci9jb3VudGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L0FuZ3VsYXI0L3Rlc3RBb3RBcHAyV29ya2luZy90ZXN0QW90QXBwMi9DbGllbnRBcHAvYXBwL2NvbXBvbmVudHMvY291bnRlci9jb3VudGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovQW5ndWxhcjQvdGVzdEFvdEFwcDJXb3JraW5nL3Rlc3RBb3RBcHAyL0NsaWVudEFwcC9hcHAvY29tcG9uZW50cy9jb3VudGVyL2NvdW50ZXIuY29tcG9uZW50LnRzLkNvdW50ZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+Q291bnRlcjwvaDE+XHJcblxyXG48cD5UaGlzIGlzIGEgc2ltcGxlIGV4YW1wbGUgb2YgYW4gQW5ndWxhciBjb21wb25lbnQuPC9wPlxyXG5cclxuPHA+Q3VycmVudCBjb3VudDogPHN0cm9uZz57eyBjdXJyZW50Q291bnQgfX08L3N0cm9uZz48L3A+XHJcblxyXG48YnV0dG9uIChjbGljayk9XCJpbmNyZW1lbnRDb3VudGVyKClcIj5JbmNyZW1lbnQ8L2J1dHRvbj5cclxuIiwiPGNvdW50ZXI+PC9jb3VudGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQSw2QkFBWTtNQUVoQjtVQUFBLDBEQUFHO1VBQUEsd0RBQXFEO1VBQUEsV0FFeEQ7VUFBQTtNQUFHLG9EQUFlO1VBQUE7VUFBQSw4QkFBUSx3Q0FBK0I7aUJBQUEsMEJBRXpEO1VBQUE7b0JBQUE7WUFBQTtZQUFBO1lBQVE7Y0FBQTtjQUFBO1lBQUE7WUFBUjtVQUFBLGdDQUFxQztNQUFrQjs7SUFGN0I7SUFBQTs7OztvQkNKMUI7TUFBQTthQUFBO1VBQUE7OzsifQ==
