/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["@media (max-width: 767px) {\n    \n    .body-content[_ngcontent-%COMP%] {\n        padding-top: 50px;\n    }\n}"];
export { styles as styles };
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map